Simplify MA_main by extending the parser
The XX_run functions are now executed by the parser (making it a
framework, oops), but it's much cleaner and makes adding new
functionality even cleaner. New commands can be added without touching
any existing file - just by adding a new file and it will set itself up.
This reduces the risk of breaking stuff.

diff --git a/package/mok b/package/mok
--- a/package/mok
+++ b/package/mok
@@ -1,159 +1,5 @@
 #!/usr/bin/env bash
 # shellcheck shell=bash disable=SC2148
-# MA - execution starts here
-
-# MA is an associative array that holds data specific to this file
-declare -A _MA
-
-# Defined in GL (globals.sh)
-declare OK ERROR STOP STDERR TRUE
-
-# Getters/Setters -------------------------------------------------------------
-
-# MA_program_args getter outputs the program arguments sent by the user.
-MA_program_args() {
-  printf '%s' "${_MA[program_args]}"
-}
-
-# Public Functions ------------------------------------------------------------
-
-# main is the start point for this application.
-# Args: arg1-N - the command line arguments entered by the user.
-MA_main() {
-
-  trap MA_cleanup EXIT
-  MA_sanity_checks || return
-  MA_register_parser_global_options || return
-
-  local retval="${OK}"
-  PA_run "$@" || retval=$?
-  if [[ ${retval} -eq ${ERROR} ]]; then
-    return "${ERROR}"
-  elif [[ ${retval} -eq ${STOP} ]]; then
-    return "${OK}"
-  fi
-
-  local cmd subcmd
-  cmd=$(PA_command) || err || return
-  subcmd=$(PA_subcommand) || err || return
-  case "${cmd}${subcmd}" in
-  create | createcluster) CC_run ;;
-  delete | deletecluster) DC_run ;;
-  build | buildimage) BI_run ;;
-  get | getcluster | getclusters) GC_run ;;
-  exec) EX_run ;;
-  *)
-    PA_usage
-    printf '\nERROR: No COMMAND specified.\n'
-    ;;
-  esac
-}
-
-# MA_register_parser_global_options adds the options callback and usage
-# callback to the Parser.
-MA_register_parser_global_options() {
-  PA_add_state "COMMAND" "version" "END" "MA_version"
-  PA_add_option_callback "" "MA_process_global_options"
-  PA_add_usage_callback "" "MA_usage"
-}
-
-# MA_version outputs the version information the exits.
-MA_version() {
-  printf 'Version: %s\n' "${MOKVERSION}"
-  exit "${OK}"
-}
-
-# MA_process_global_options is called by the parser when a global option is
-# encountered for processing.
-# Args: arg1 - the global option that was found.
-MA_process_global_options() {
-  case "$1" in
-  -h | --help)
-    PA_usage
-    return "${STOP}"
-    ;;
-  -p | --plain)
-    UT_set_plain "${TRUE}"
-    ;;
-  *)
-    printf 'INTERNAL ERROR: Invalid global option, "%s".' "$1"
-    return "${ERROR}"
-    ;;
-  esac
-}
-
-# MA_cleanup is called from an EXIT trap only, when the program exits, and
-# calls every other function matching the pattern '^.._cleanup'.
-# Args: No args expected.
-MA_cleanup() {
-  local retval="${OK}" funcs func
-  funcs=$(declare -F | awk '{print $NF;}' | grep '^.._cleanup')
-  for func in ${funcs}; do
-    [[ ${func} == "${FUNCNAME[0]}" ]] && continue
-    eval "${func}" || retval=$?
-  done
-  return "${retval}"
-}
-
-# MA_sanity_checks is expected to run some quick and simple checks to
-# see if key components are available before MA_main is called.
-# Args: No args expected.
-MA_sanity_checks() {
-
-  local binary
-
-  for binary in tac column tput grep sed; do
-    if ! command -v "${binary}" >&/dev/null; then
-      printf 'ERROR: "%s" binary not found in path. Aborting.' "${binary}" \
-        >"${STDERR}"
-      return "${ERROR}"
-    fi
-  done
-
-  # Disable terminal escapes (colours) if stdout is not a terminal
-  [ -t 1 ] || UT_disable_colours
-}
-
-# MA_usage outputs help text for all components then quits with no error.  This
-# is registered as a callback in the Parser in
-# MA_register_parser_global_options.
-# Args: None expected.
-MA_usage() {
-
-  cat <<'EnD'
-Usage: mok [-h] <command> [subcommand] [ARGS...]
- 
-Global options:
-  --help
-  -h     - This help text
-  --plain
-  -p     - Plain output. No colours or animations.
- 
-Where command can be one of:
-  create  - Add item(s) to the system.
-  delete  - Delete item(s) from the system.
-  build   - Build item(s) used by the system.
-  get     - Get details about items in the system.
-  exec    - 'Log in' to the container.
-  version - Display version information.
-
-For help on a specific command, run:
-  mok <command> --help
-EnD
-}
-
-# MA_new sets the initial values for the _MA associative array
-_MA_new() {
-  _MA[program_args]="$*"
-}
-
-# Initialise _MA
-_MA_new "$@" || exit 1
-
-# vim helpers -----------------------------------------------------------------
-#include globals.sh
-# vim:ft=sh:sw=2:et:ts=2:
-# shellcheck shell=bash disable=SC2148
 # PA - PArser
 
 # _PA holds data specific to parsing the command line arguments.
@@ -237,6 +83,15 @@ PA_add_state() {
   _PA[statecallbacks]+="$1,$2,$3,$4 "
 }
 
+# PA_add_run_callback adds a callback to the list of callbacks used for
+# running the user defined entrypoint function.
+# Args: arg1 - The value of the state to match. Probably like:
+#              "commandsubcommand" "function"
+#       arg2 - The function to call.
+PA_add_run_callback() {
+  _PA[runcallbacks]+="$1,$2 "
+}
+
 # PA_run implements an interleaved state machine to process the
 # user request. It allows for strict checking of arguments and args. All
 # command line arguments are processed in order from left to right.
@@ -253,6 +108,8 @@ PA_add_state() {
 #
 # Args: arg1-N - The arguments given to mok by the user on the command line
 PA_run() {
+
+  local retval=${OK}
 
   set -- "$@"
   local ARGN=$# ARGNUM=0 retval=0
@@ -315,6 +172,17 @@ PA_run() {
     ARGN=$((ARGN - 1))
   done
 
+  # Run the user defined entrypoint function:
+  for item in ${_PA[runcallbacks]}; do
+    IFS=, read -r stateval func <<<"${item}"
+    [[ ${stateval} == "${_PA[command]}${_PA[subcommand]}" ]] && {
+      eval "${func}" || retval=$?
+      return "${retval}"
+    }
+  done
+
+  PA_usage
+
   return "${OK}"
 }
 
@@ -346,6 +214,8 @@ _PA_new() {
   _PA[state]="COMMAND"
   _PA[optscallbacks]=
   _PA[usagecallbacks]=
+  _PA[statecallbacks]=
+  _PA[runcallbacks]=
   # The return value if the caller asked for an extra shift:
   _PA[shift]=126
 }
@@ -901,6 +771,10 @@ _GC_new() {
   PA_add_usage_callback "get" "GC_usage" || return
   PA_add_usage_callback "getcluster" "GC_usage" || return
   PA_add_usage_callback "getclusters" "GC_usage" || return
+
+  # Set up the parser's run callbacks
+  PA_add_run_callback "getcluster" "GC_run"
+  PA_add_run_callback "getclusters" "GC_run"
 }
 
 # GC_sanity_checks is expected to run some quick and simple checks to
@@ -1064,6 +938,9 @@ _EX_new() {
   # Set up the parser's option callbacks
   PA_add_option_callback "exec" "EX_process_options" || return
   PA_add_usage_callback "exec" "EX_usage" || return
+
+  # Set up the parser's run callbacks
+  PA_add_run_callback "exec" "EX_run"
 }
 
 # EX_sanity_checks is expected to run some quick and simple checks to
@@ -1229,6 +1106,9 @@ _DC_new() {
   # Set up the parser's usage callbacks
   PA_add_usage_callback "delete" "DC_usage" || return
   PA_add_usage_callback "deletecluster" "DC_usage" || return
+
+  # Set up the parser's run callbacks
+  PA_add_run_callback "deletecluster" "DC_run"
 }
 
 # DC_sanity_checks is expected to run some quick and simple checks to see if it
@@ -1408,8 +1288,8 @@ create cluster [flags] options:
                   master nodes so that pods are schedulable on those nodes.
   --tailf - Show the log output whilst creating the cluster.
   --publish - Publish port 6443 for the master node, or the load balancer if
-              it's enabled, to allow external access to the cluster.
-              The IP address of the default route interface is used.
+              it's enabled, for external kubectl access to the cluster. The IP
+              address of the default route interface is added to the cert.
 
 
 EnD
@@ -1498,6 +1378,10 @@ _CC_new() {
   # Set up the parser's usage callbacks
   PA_add_usage_callback "create" "CC_usage" || return
   PA_add_usage_callback "createcluster" "CC_usage" || return
+
+  # Set up the parser's run callbacks
+  PA_add_run_callback "createcluster" "CC_run"
+  PA_add_run_callback "createclusters" "CC_run"
 }
 
 # CC_sanity_checks is expected to run some quick and simple checks to see if it
@@ -2691,6 +2575,9 @@ _BI_new() {
   # Set up the parser's usage callbacks
   PA_add_usage_callback "build" "BI_usage" || return
   PA_add_usage_callback "buildimage" "BI_usage" || return
+
+  # Set up the parser's run callbacks
+  PA_add_run_callback "buildimage" "BI_run"
 }
 
 # BI_sanity_checks is expected to run some quick and simple checks to
@@ -4194,6 +4081,140 @@ JSONPath_throw() {
 JSONPath_new || exit 1
 
 # vi: expandtab sw=2 ts=2
+# shellcheck shell=bash disable=SC2148
+# MA - execution starts here
+
+# MA is an associative array that holds data specific to this file
+declare -A _MA
+
+# Defined in GL (globals.sh)
+declare OK ERROR STOP STDERR TRUE
+
+# Getters/Setters -------------------------------------------------------------
+
+# MA_program_args getter outputs the program arguments sent by the user.
+MA_program_args() {
+  printf '%s' "${_MA[program_args]}"
+}
+
+# Public Functions ------------------------------------------------------------
+
+# main is the start point for this application.
+# Args: arg1-N - the command line arguments entered by the user.
+MA_main() {
+  local retval="${OK}"
+
+  trap MA_cleanup EXIT
+  MA_sanity_checks || return
+  PA_run "$@" || retval=$?
+
+  exit "${retval}"
+}
+
+# MA_version outputs the version information the exits.
+MA_version() {
+  printf 'Version: %s\n' "${MOKVERSION}"
+  exit "${OK}"
+}
+
+# MA_process_global_options is called by the parser when a global option is
+# encountered for processing.
+# Args: arg1 - the global option that was found.
+MA_process_global_options() {
+  case "$1" in
+  -h | --help)
+    PA_usage
+    return "${STOP}"
+    ;;
+  -p | --plain)
+    UT_set_plain "${TRUE}"
+    ;;
+  *)
+    printf 'INTERNAL ERROR: Invalid global option, "%s".' "$1"
+    return "${ERROR}"
+    ;;
+  esac
+}
+
+# MA_cleanup is called from an EXIT trap only, when the program exits, and
+# calls every other function matching the pattern '^.._cleanup'.
+# Args: No args expected.
+MA_cleanup() {
+  local retval="${OK}" funcs func
+  funcs=$(declare -F | awk '{print $NF;}' | grep '^.._cleanup')
+  for func in ${funcs}; do
+    [[ ${func} == "${FUNCNAME[0]}" ]] && continue
+    eval "${func}" || retval=$?
+  done
+  return "${retval}"
+}
+
+# MA_sanity_checks is expected to run some quick and simple checks to
+# see if key components are available before MA_main is called.
+# Args: No args expected.
+MA_sanity_checks() {
+
+  local binary
+
+  for binary in tac column tput grep sed ip cut; do
+    if ! command -v "${binary}" >&/dev/null; then
+      printf 'ERROR: "%s" binary not found in path. Aborting.' "${binary}" \
+        >"${STDERR}"
+      return "${ERROR}"
+    fi
+  done
+
+  # Disable terminal escapes (colours) if stdout is not a terminal
+  [ -t 1 ] || UT_disable_colours
+}
+
+# MA_usage outputs help text for all components then quits with no error.  This
+# is registered as a callback in the Parser, see _MA_new
+# Args: None expected.
+MA_usage() {
+
+  cat <<'EnD'
+Usage: mok [-h] <command> [subcommand] [ARGS...]
+ 
+Global options:
+  --help
+  -h     - This help text
+  --plain
+  -p     - Plain output. No colours or animations.
+ 
+Where command can be one of:
+  create  - Add item(s) to the system.
+  delete  - Delete item(s) from the system.
+  build   - Build item(s) used by the system.
+  get     - Get details about items in the system.
+  exec    - 'Log in' to the container.
+  version - Display version information.
+
+For help on a specific command, run:
+  mok <command> --help
+EnD
+}
+
+# MA_new sets the initial values for the _MA associative array
+_MA_new() {
+  _MA[program_args]="$*"
+
+  # Program the parser's state machine
+  PA_add_state "COMMAND" "version" "END" "MA_version"
+
+  # Set up the parser's option callbacks
+  PA_add_option_callback "" "MA_process_global_options"
+
+  # Set up the parser's usage callbacks
+  PA_add_usage_callback "" "MA_usage"
+}
+
+# Initialise _MA
+_MA_new "$@" || exit 1
+
+# vim helpers -----------------------------------------------------------------
+#include globals.sh
+# vim:ft=sh:sw=2:et:ts=2:
 if [ "$0" = "${BASH_SOURCE[0]}" ] || [ -z "${BASH_SOURCE[0]}" ]; then
   MA_main "$@"
 fi
